-- Inserts CATEGORÍAS (40 sobre deportes)
INSERT INTO categorias (categoria) VALUES ('Fútbol');
INSERT INTO categorias (categoria) VALUES ('Baloncesto');
INSERT INTO categorias (categoria) VALUES ('Bolos');
INSERT INTO categorias (categoria) VALUES ('Tenis');
INSERT INTO categorias (categoria) VALUES ('Golf');
INSERT INTO categorias (categoria) VALUES ('Natación');
INSERT INTO categorias (categoria) VALUES ('Atletismo');
INSERT INTO categorias (categoria) VALUES ('Ciclismo');
INSERT INTO categorias (categoria) VALUES ('Rugby');
INSERT INTO categorias (categoria) VALUES ('Voleibol');
INSERT INTO categorias (categoria) VALUES ('Volei Playa');
INSERT INTO categorias (categoria) VALUES ('Paintball');
INSERT INTO categorias (categoria) VALUES ('Hockey');
INSERT INTO categorias (categoria) VALUES ('Boxeo');
INSERT INTO categorias (categoria) VALUES ('Artes marciales');
INSERT INTO categorias (categoria) VALUES ('Esgrima');
INSERT INTO categorias (categoria) VALUES ('Surf');
INSERT INTO categorias (categoria) VALUES ('Escalada');
INSERT INTO categorias (categoria) VALUES ('Esquí');
INSERT INTO categorias (categoria) VALUES ('Snowboard');
INSERT INTO categorias (categoria) VALUES ('Patinaje');
INSERT INTO categorias (categoria) VALUES ('Gimnasia');
INSERT INTO categorias (categoria) VALUES ('Yoga');
INSERT INTO categorias (categoria) VALUES ('Pilates');
INSERT INTO categorias (categoria) VALUES ('Baile');
INSERT INTO categorias (categoria) VALUES ('Parkour');
INSERT INTO categorias (categoria) VALUES ('Tiro al blanco');
INSERT INTO categorias (categoria) VALUES ('Pesca');
INSERT INTO categorias (categoria) VALUES ('Caza');
INSERT INTO categorias (categoria) VALUES ('Buceo');
INSERT INTO categorias (categoria) VALUES ('Kitesurf');
INSERT INTO categorias (categoria) VALUES ('Alpinismo');
INSERT INTO categorias (categoria) VALUES ('Skateboarding');
INSERT INTO categorias (categoria) VALUES ('Triatlón');
INSERT INTO categorias (categoria) VALUES ('Motociclismo');
INSERT INTO categorias (categoria) VALUES ('Automovilismo');
INSERT INTO categorias (categoria) VALUES ('Vela');
INSERT INTO categorias (categoria) VALUES ('Canotaje');
INSERT INTO categorias (categoria) VALUES ('Windsurf');
INSERT INTO categorias (categoria) VALUES ('Equitación');
INSERT INTO categorias (categoria) VALUES ('Paracaidismo');
INSERT INTO categorias (categoria) VALUES ('Ala delta');


-- Inserts CATEGORÍAS (40 sobre videojuegos)
INSERT INTO categorias (categoria) VALUES ('Fortnite');
INSERT INTO categorias (categoria) VALUES ('League of Legends');
INSERT INTO categorias (categoria) VALUES ('Valorant');
INSERT INTO categorias (categoria) VALUES ('Call of Duty');
INSERT INTO categorias (categoria) VALUES ('Overwatch');
INSERT INTO categorias (categoria) VALUES ('Rocket League');
INSERT INTO categorias (categoria) VALUES ('Among Us');
INSERT INTO categorias (categoria) VALUES ('Minecraft');
INSERT INTO categorias (categoria) VALUES ('Super Smash Bros.');
INSERT INTO categorias (categoria) VALUES ('Counter-Strike: Global Offensive');
INSERT INTO categorias (categoria) VALUES ('Apex Legends');
INSERT INTO categorias (categoria) VALUES ('Rainbow Six Siege');
INSERT INTO categorias (categoria) VALUES ('FIFA');
INSERT INTO categorias (categoria) VALUES ('NBA 2K');
INSERT INTO categorias (categoria) VALUES ('Mario Kart');
INSERT INTO categorias (categoria) VALUES ('Dead by Daylight');
INSERT INTO categorias (categoria) VALUES ('Phasmophobia');
INSERT INTO categorias (categoria) VALUES ('Fall Guys: Ultimate Knockout');
INSERT INTO categorias (categoria) VALUES ('World of Warcraft');
INSERT INTO categorias (categoria) VALUES ('Dota 2');
INSERT INTO categorias (categoria) VALUES ('Smite');
INSERT INTO categorias (categoria) VALUES ('Brawlhalla');
INSERT INTO categorias (categoria) VALUES ('Castle Crashers');
INSERT INTO categorias (categoria) VALUES ('Among Us');
INSERT INTO categorias (categoria) VALUES ('Mortal Kombat');
INSERT INTO categorias (categoria) VALUES ('Street Fighter');
INSERT INTO categorias (categoria) VALUES ('Tekken');
INSERT INTO categorias (categoria) VALUES ('Super Mario Party');
INSERT INTO categorias (categoria) VALUES ('Mario Tennis');
INSERT INTO categorias (categoria) VALUES ('Worms');
INSERT INTO categorias (categoria) VALUES ('Sea of Thieves');
INSERT INTO categorias (categoria) VALUES ('PlayerUnknown\'s Battlegrounds');
INSERT INTO categorias (categoria) VALUES ('Grand Theft Auto Online');
INSERT INTO categorias (categoria) VALUES ('Rust');
INSERT INTO categorias (categoria) VALUES ('The Elder Scrolls Online');
INSERT INTO categorias (categoria) VALUES ('Warframe');
INSERT INTO categorias (categoria) VALUES ('Terraria');
INSERT INTO categorias (categoria) VALUES ('Roblox');
INSERT INTO categorias (categoria) VALUES ('Realidad Virtual');


-- Inserts CATEGORÍAS (40 sobre actividades en grupo/al aire libre)
INSERT INTO categorias (categoria) VALUES ('Senderismo en grupo');
INSERT INTO categorias (categoria) VALUES ('Picnic');
INSERT INTO categorias (categoria) VALUES ('Camping');
INSERT INTO categorias (categoria) VALUES ('Karaoke');
INSERT INTO categorias (categoria) VALUES ('Juegos de mesa');
INSERT INTO categorias (categoria) VALUES ('Fiesta temática');
INSERT INTO categorias (categoria) VALUES ('Fiesta');
INSERT INTO categorias (categoria) VALUES ('Cocina');
INSERT INTO categorias (categoria) VALUES ('Barbacoa');
INSERT INTO categorias (categoria) VALUES ('Gastronomía');
INSERT INTO categorias (categoria) VALUES ('Concierto');
INSERT INTO categorias (categoria) VALUES ('Parque de atracciones');
INSERT INTO categorias (categoria) VALUES ('Manualidades');
INSERT INTO categorias (categoria) VALUES ('Museo');
INSERT INTO categorias (categoria) VALUES ('Cine al aire libre');
INSERT INTO categorias (categoria) VALUES ('Escape room');
INSERT INTO categorias (categoria) VALUES ('Feria');
INSERT INTO categorias (categoria) VALUES ('Marítimo');
INSERT INTO categorias (categoria) VALUES ('Playa');
INSERT INTO categorias (categoria) VALUES ('Juegos de rol');
INSERT INTO categorias (categoria) VALUES ('Observación de aves');
INSERT INTO categorias (categoria) VALUES ('Fotografía');
INSERT INTO categorias (categoria) VALUES ('Piscina');
INSERT INTO categorias (categoria) VALUES ('Zoo');
INSERT INTO categorias (categoria) VALUES ('Torneo');
INSERT INTO categorias (categoria) VALUES ('Disfraces');
INSERT INTO categorias (categoria) VALUES ('Fiesta de disfraces');
INSERT INTO categorias (categoria) VALUES ('Taller de improvisación');
INSERT INTO categorias (categoria) VALUES ('Dibujo');
INSERT INTO categorias (categoria) VALUES ('Restaurante');
INSERT INTO categorias (categoria) VALUES ('Arborismo');


-- Inserts CATEGORÍAS (40 sobre comida/gastronomía)
INSERT INTO categorias (categoria) VALUES ('Comida italiana');
INSERT INTO categorias (categoria) VALUES ('Comida mexicana');
INSERT INTO categorias (categoria) VALUES ('Comida japonesa');
INSERT INTO categorias (categoria) VALUES ('Comida francesa');
INSERT INTO categorias (categoria) VALUES ('Comida tailandesa');
INSERT INTO categorias (categoria) VALUES ('Comida india');
INSERT INTO categorias (categoria) VALUES ('Comida española');
INSERT INTO categorias (categoria) VALUES ('Comida china');
INSERT INTO categorias (categoria) VALUES ('Comida árabe');
INSERT INTO categorias (categoria) VALUES ('Comida coreana');
INSERT INTO categorias (categoria) VALUES ('Comida vegetariana');
INSERT INTO categorias (categoria) VALUES ('Comida vegana');
INSERT INTO categorias (categoria) VALUES ('Repostería');
INSERT INTO categorias (categoria) VALUES ('Hamburguesas');
INSERT INTO categorias (categoria) VALUES ('Postres caseros');
INSERT INTO categorias (categoria) VALUES ('Pizza');
INSERT INTO categorias (categoria) VALUES ('Helados y sorbetes');
INSERT INTO categorias (categoria) VALUES ('Desayunos');
INSERT INTO categorias (categoria) VALUES ('Brunch');
INSERT INTO categorias (categoria) VALUES ('Tapas');
INSERT INTO categorias (categoria) VALUES ('Sushi');
INSERT INTO categorias (categoria) VALUES ('Buffet');
INSERT INTO categorias (categoria) VALUES ('Barbacoa');
INSERT INTO categorias (categoria) VALUES ('Mariscos');
INSERT INTO categorias (categoria) VALUES ('Asado');
INSERT INTO categorias (categoria) VALUES ('Ensaladas');
INSERT INTO categorias (categoria) VALUES ('Sándwiches');

